name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.0-nullsafety.3
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.0
  geolocator: ^9.0.2
  permission_handler: ^10.0.1
  provider: ^6.0.3
  google_maps_webservice: ^0.0.19
  google_api_headers: ^1.3.0
  tuple: ^2.0.0-nullsafety.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
